---
- name: Create a Fedora VM with KubeVirt on OpenShift
  gather_facts: false
  hosts: all  # Target all hosts in your inventory
  vars:
    kubevirt_instancetype: u1.medium
    kubevirt_preference: fedora
    kubevirt_namespace: yl-aap
    default_username: fedora
    default_password: P@$$w0rd
    default_root_password_hashed: $6$2K4V7ulKbvCEigka$ALf90b/xdWgfFpvxFJIGGMhX6elVd32TjxtImOe1TUsMOOiXeMLWuboJIroO1KUX5qc.iHVO6TLI0Nte9uphs/
    kubevirt_vm_name: fedora-httpd
    injected_ssh_public_key: "SSH-RSA AAAAB3NzaC1yc2EAAAADAQABAAACAQC3v5Z7"
    virtctl_timeout: 90  # Timeout for virtctl console command

  tasks:
    - name: "Create project"
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ kubevirt_namespace }}"

    - name: "Create virtual machine {{ kubevirt_preference }}"
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: "{{ kubevirt_vm_name }}"
        namespace: "{{ kubevirt_namespace }}"
        labels:
          app: httpd
        instancetype:
          name: "{{ kubevirt_instancetype }}"
        preference:
          name: "{{ kubevirt_preference }}"
        spec:
          domain:
            devices:
              interfaces:
                - name: default
                  masquerade: {}
          networks:
            - name: default
              pod: {}
          volumes:
            - containerDisk:
                image: quay.io/containerdisks/{{ kubevirt_preference }}:latest
              name: containerdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  disable_root: false
                  user: {{ default_username }}
                  password: {{ default_password }}
                  chpasswd: { expire: False }
                  users:
                    - name: root
                      shell: /bin/bash
                      lock_passwd: false
                      passwd: "{{ default_root_password_hashed }}"
                    - name: {{ default_username }}
                      passwd: {{ default_password }}
                      chpasswd: { expire: False }
                      lock_passwd: false
                  ssh_pwauth: true
                  ssh_authorized_keys:
                    - {{ injected_ssh_public_key }}
                  packages:
                    - openssh-server
                  runcmd:
                    - [ systemctl, enable, sshd ]
                    - [ systemctl, start, sshd ]
                    - firewall-cmd --zone=public --add-service=ssh --permanent
                    - firewall-cmd --reload
              name: cloudinit

    - name: Wait for virtual machine IP to be populated
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ kubevirt_vm_name }}"
        namespace: "{{ kubevirt_namespace }}"
      register: vmi
      retries: 60
      delay: 10
      until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0

    - name: Expose SSH and HTTP ports via NodePort
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ kubevirt_vm_name }}-svc"
            namespace: "{{ kubevirt_namespace }}"
          spec:
            type: NodePort
            selector:
              vm.kubevirt.io/name: "{{ kubevirt_vm_name }}"
            ports:
              - name: ssh
                port: 22000
                targetPort: 22
                protocol: TCP
