---
- name: Install virtctl and run httpd setup in VM
  hosts: all
  gather_facts: false
  tasks:
    - name: Create kubeconfig from token
      ansible.builtin.copy:
        dest: /tmp/kubeconfig
        mode: '0600'
        content: |
          apiVersion: v1
          kind: Config
          clusters:
          - name: api
            cluster:
              server: {{ lookup('env', 'K8S_AUTH_HOST') }}
              insecure-skip-tls-verify: true
          users:
          - name: default-user
            user:
              token: {{ lookup('env', 'K8S_AUTH_API_KEY') }}
          contexts:
          - name: default-context
            context:
              cluster: api
              user: default-user
          current-context: default-context

    - name: Generate script from template
      ansible.builtin.template:
        src: virtctl-console.py.j2
        dest: /tmp/virtctl-console.py
        mode: '0755'

    - name: "Run the script, once finished, mark this task as done"
      ansible.builtin.command: python3 /tmp/virtctl-console.py
      register: virtctl_console_result
      changed_when: virtctl_console_result.rc == 0
      failed_when: virtctl_console_result.rc != 0
